name: Push to main
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'
      - 'md_profiles/**'
      - 'md_catalogs/**'

jobs:

  autosync:
    name: Auto-update content
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@v2.1.0
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"contents": "write"}
      - name: Clone
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get_installation_token.outputs.token }}
      - name: Sync catalogs
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@v0.10.0
        with:
          markdown_path: "md_catalogs"
          oscal_model: "catalog"
          commit_message: "Auto-sync catalog content [skip ci]"
      - name: Sync profiles
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@v0.10.0
        with:
          markdown_path: "md_profiles"
          oscal_model: "profile"
          commit_message: "Auto-sync profile content [skip ci]"
